// Frontend_App/src/app/examples/security/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { SecurityService } from '../../../services/security.service';
import { Router } from '@angular/router';
import { User } from 'app/models/user.model';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})

export class LoginComponent implements OnInit {

    data : Date = new Date();
    e_mail:string="";
    password:string="";
    focus;
    focus1;
    
    constructor(private securityService: SecurityService,
        private router: Router) { }

        login():void{  
          let newUser:User={
            e_mail:this.e_mail,
            password:this.password
            
          }
          this.securityService.login(newUser).subscribe(
            data=>{
              this.router.navigate(['pages/dashboard']);
              this.securityService.saveDataSession(data);
            }
      );
  }
    
    ngOnInit(): void {
      var body = document.getElementsByTagName('body')[0];
        body.classList.add('login-page');

        var navbar = document.getElementsByTagName('nav')[0];
        navbar.classList.add('navbar-transparent');
    }
                
    ngOnDestroy(){
        var body = document.getElementsByTagName('body')[0];
        body.classList.remove('login-page');

        var navbar = document.getElementsByTagName('nav')[0];
        navbar.classList.remove('navbar-transparent');
    }

}


<div class="page-header" filter-color="orange">
    <div class="page-header-image" style="background-image:url(assets/img/login.jpg)"></div>
    <div class="container">
        <div class="col-md-4 content-center">
            <div class="card card-login card-plain">
                <form class="form" method="" action="">
                    <div class="header header-primary text-center">
                        <div class="logo-container">
                            <img src="assets/img/now-logo.png" alt="">
                        </div>
                    </div>
                    <div class="content">
                      <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                        <div class="input-group-prepend">
                            <span class="input-group-text">  <i class="now-ui-icons users_circle-08"></i></span>
                        </div>
                          <input type="text" class="form-control" placeholder="First Name..." (focus)="focus=true" (blur)="focus=false" >
                      </div>
                      <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus1===true}">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="now-ui-icons text_caps-small"></i></span>
                        </div>
                          <input type="text" placeholder="Last Name..." class="form-control" (focus)="focus1=true" (blur)="focus1=false"/>
                      </div>
                    </div>
                    <div class="footer text-center">
                        <a href="#pablo" class="btn btn-primary btn-round btn-lg btn-block">Get Started</a>
                    </div>
                    <div class="pull-left">
                        <h6>
                            <a href="#pablo" class="link">login</a>
                        </h6>
                    </div>
                    <div class="pull-right">
                        <h6>
                            <a href="#pablo" class="link">Need Help?</a>
                        </h6>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <nav>
                <ul>
                    <li>
                        <a href="https://www.creative-tim.com">
                            Creative Tim
                        </a>
                    </li>
                    <li>
                        <a href="https://www.creative-tim.com/about-us">
                            About Us
                        </a>
                    </li>
                    <li>
                        <a href="http://blog.creative-tim.com">
                            Blog
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/creativetimofficial/now-ui-kit/blob/master/LICENSE.md">
                            MIT License
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright">
                &copy;
              {{data | date: 'yyyy'}}, Designed by
                <a href="https://www.invisionapp.com" target="_blank" rel="noopener">Invision</a>. Coded by
                <a href="https://www.creative-tim.com" target="_blank" rel="noopener">Creative Tim</a>.
            </div>
        </div>
    </footer>
</div>

// Frontend_App/src/pages/Login.vue
<template>
  <div class="page-header clear-filter" filter-color="orange">
    <div
      class="page-header-image"
      style="background-image: url('img/login.jpg')"
    ></div>

    <div class="content">
      <div class="container">
        <div class="col-md-5 ml-auto mr-auto">
          <card type="login" plain>

            <div slot="header" class="logo-container">
              <img v-lazy="'img/now-logo.png'" alt="" />
            </div>
          
  
            <input
              class="no-border input-lg"
              addon-left-icon="now-ui-icons users_circle-08"
              placeholder="Usrename"
              type="username" 
              v-model="data.username"
            >
           

            <input
              class="no-border input-lg"
              addon-left-icon="now-ui-icons text_caps-small"
              placeholder="Password"
              type="password" 
              v-model="data.password"
            >
       

            <button 
            @click="login"
            class="btn btn-primary btn-round btn-lg btn-block"
            >
            Login</button>



           

            <template slot="raw-content">
              <div class="pull-left">
                <h6>
                  <a href="#pablo" class="link footer-link">Create Account</a>
                </h6>
              </div>
              <div class="pull-right">
                <h6>
                  <a href="#pablo" class="link footer-link">Need Help?</a>
                </h6>
              </div>
            </template>
          </card>
        </div>
      </div>
    </div>
    <main-footer></main-footer>
  </div>
</template>


<script>
import { Card, Button, FormGroupInput } from '@/components';
import MainFooter from '@/layout/MainFooter';
import axios from 'axios';

export default {
  data() {
    return {
        data: {username: '', password: ''
      }
    };

  },
  components: {
    Card,
    MainFooter,
    [Button.name]: Button,
    [FormGroupInput.name]: FormGroupInput
  },
  methods: {
    async login() {
     try {
        const response = await axios.post('http://127.0.0.1:7777/login', {
          username: this.data.username,
          password: this.data.password,
        });

        if  (response.data.msg === 'Token Created') {
              localStorage.setItem('token', response.data.token);
              this.$router.push('/profile');
        } else {
            alert('Login failed');
        }
        } catch (error) {
            console.error(error);
            alert('An error occurred');
    }
  }
  }
};
</script>
<style></style>
